GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6213822a8e9e1d750afcd75e

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "nice",
    "subscribedToChannel": "Web Dev Simplified"
}
###
DELETE http://localhost:3000/subscribers/621385307a997ddc7b0ce228
###
PATCH http://localhost:3000/subscribers/621375a81237eebcc160571a
Content-Type: application/json

{
    "name":"amazing girl"
}